version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ibpi-network
    labels:
      - "com.example.description=IBPI React Application"
      - "com.example.version=1.0"

  sms-proxy:
    build:
      context: .
      dockerfile: Dockerfile.sms
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - ibpi-network
    depends_on:
      - web

networks:
  ibpi-network:
    driver: bridge

volumes:
  nginx-cache:
    driver: local